// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use gio_sys;
use glib;
use glib::object::IsA;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::object::ObjectType as ObjectType_;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::signal::connect_raw;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::signal::SignalHandlerId;
use glib::translate::*;
#[cfg(any(feature = "v2_60", feature = "dox"))]
use glib::GString;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib_sys;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use std::boxed::Box as Box_;
use std::fmt;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use std::mem::transmute;
use AsyncResult;
use Cancellable;

glib_wrapper! {
    pub struct Task(Object<gio_sys::GTask, gio_sys::GTaskClass, TaskClass>) @implements AsyncResult;

    match fn {
        get_type => || gio_sys::g_task_get_type(),
    }
}

impl Task {
    //pub fn attach_source<P: Fn() -> bool + 'static>(&self, source: &glib::Source, callback: P) {
    //    unsafe { TODO: call gio_sys:g_task_attach_source() }
    //}

    pub fn get_cancellable(&self) -> Option<Cancellable> {
        unsafe { from_glib_none(gio_sys::g_task_get_cancellable(self.to_glib_none().0)) }
    }

    pub fn get_check_cancellable(&self) -> bool {
        unsafe { from_glib(gio_sys::g_task_get_check_cancellable(self.to_glib_none().0)) }
    }

    #[cfg(any(feature = "v2_44", feature = "dox"))]
    pub fn get_completed(&self) -> bool {
        unsafe { from_glib(gio_sys::g_task_get_completed(self.to_glib_none().0)) }
    }

    pub fn get_context(&self) -> Option<glib::MainContext> {
        unsafe { from_glib_none(gio_sys::g_task_get_context(self.to_glib_none().0)) }
    }

    #[cfg(any(feature = "v2_60", feature = "dox"))]
    pub fn get_name(&self) -> Option<GString> {
        unsafe { from_glib_none(gio_sys::g_task_get_name(self.to_glib_none().0)) }
    }

    pub fn get_return_on_cancel(&self) -> bool {
        unsafe { from_glib(gio_sys::g_task_get_return_on_cancel(self.to_glib_none().0)) }
    }

    //pub fn get_source_tag(&self) -> /*Unimplemented*/Option<Fundamental: Pointer> {
    //    unsafe { TODO: call gio_sys:g_task_get_source_tag() }
    //}

    //pub fn get_task_data(&self) -> /*Unimplemented*/Option<Fundamental: Pointer> {
    //    unsafe { TODO: call gio_sys:g_task_get_task_data() }
    //}

    pub fn had_error(&self) -> bool {
        unsafe { from_glib(gio_sys::g_task_had_error(self.to_glib_none().0)) }
    }

    pub fn return_error_if_cancelled(&self) -> bool {
        unsafe {
            from_glib(gio_sys::g_task_return_error_if_cancelled(
                self.to_glib_none().0,
            ))
        }
    }

    //pub fn return_new_error(&self, domain: glib::Quark, code: i32, format: &str, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs) {
    //    unsafe { TODO: call gio_sys:g_task_return_new_error() }
    //}

    //pub fn run_in_thread(&self, task_func: /*Unimplemented*/FnOnce(&Task, &glib::Object, /*Unimplemented*/Option<Fundamental: Pointer>, Option<&Cancellable>)) {
    //    unsafe { TODO: call gio_sys:g_task_run_in_thread() }
    //}

    //pub fn run_in_thread_sync(&self, task_func: /*Unimplemented*/FnOnce(&Task, &glib::Object, /*Unimplemented*/Option<Fundamental: Pointer>, Option<&Cancellable>)) {
    //    unsafe { TODO: call gio_sys:g_task_run_in_thread_sync() }
    //}

    pub fn set_check_cancellable(&self, check_cancellable: bool) {
        unsafe {
            gio_sys::g_task_set_check_cancellable(
                self.to_glib_none().0,
                check_cancellable.to_glib(),
            );
        }
    }

    #[cfg(any(feature = "v2_60", feature = "dox"))]
    pub fn set_name(&self, name: Option<&str>) {
        unsafe {
            gio_sys::g_task_set_name(self.to_glib_none().0, name.to_glib_none().0);
        }
    }

    pub fn set_return_on_cancel(&self, return_on_cancel: bool) -> bool {
        unsafe {
            from_glib(gio_sys::g_task_set_return_on_cancel(
                self.to_glib_none().0,
                return_on_cancel.to_glib(),
            ))
        }
    }

    //pub fn set_source_tag(&self, source_tag: /*Unimplemented*/Option<Fundamental: Pointer>) {
    //    unsafe { TODO: call gio_sys:g_task_set_source_tag() }
    //}

    //pub fn set_task_data(&self, task_data: /*Unimplemented*/Option<Fundamental: Pointer>) {
    //    unsafe { TODO: call gio_sys:g_task_set_task_data() }
    //}

    pub fn is_valid<P: IsA<AsyncResult>, Q: IsA<glib::Object>>(
        result: &P,
        source_object: Option<&Q>,
    ) -> bool {
        unsafe {
            from_glib(gio_sys::g_task_is_valid(
                result.as_ref().to_glib_none().0,
                source_object.map(|p| p.as_ref()).to_glib_none().0,
            ))
        }
    }

    //pub fn report_error<P: FnOnce(Result<(), glib::Error>) + 'static>(source_object: Option<&glib::Object>, callback: P, source_tag: /*Unimplemented*/Option<Fundamental: Pointer>, error: &mut glib::Error) {
    //    unsafe { TODO: call gio_sys:g_task_report_error() }
    //}

    //pub fn report_new_error<P: FnOnce(Result<(), glib::Error>) + 'static>(source_object: Option<&glib::Object>, callback: P, source_tag: /*Unimplemented*/Option<Fundamental: Pointer>, domain: glib::Quark, code: i32, format: &str, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs) {
    //    unsafe { TODO: call gio_sys:g_task_report_new_error() }
    //}

    #[cfg(any(feature = "v2_44", feature = "dox"))]
    pub fn connect_property_completed_notify<F: Fn(&Task) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn notify_completed_trampoline<F: Fn(&Task) + 'static>(
            this: *mut gio_sys::GTask,
            _param_spec: glib_sys::gpointer,
            f: glib_sys::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::completed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_completed_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for Task {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Task")
    }
}
